var intro_availibility_general, cuerpo_availibility_general, cierre_availibility_general, intro_availibility_Argentina, cuerpo_availibility_Argentina, cierre_availibility_argentina, intro_eb_general, cuerpo1_ebp_argentina, cuerpo1_ebp_chile, cuerpo1_ebp_colombia, cuerpo1_ebp_mexico, cuerpo1_ebp_peru, cuerpo2_eb_general, cierre_eb_general, intro_void_argentina, cuerpo1_void_argentina, cuerpo2_void_argentina, cierre_void_argentina, intro_void_general, cuerpo1_void_general, cuerpo2_void_general, cierre_void_general, intro_low_general, cuerpo1_low_general, cuerpo2_low_chile, cuerpo3_low_chile, cuerpo2_low_colombia, cuerpo3_low_colombia, cuerpo2_low_mexico,cuerpo2_low_peru, cuerpo3_low_peru, cierre_low_general, intro_low_argentina, cuerpo1_low_argentina, cuerpo2_low_argentina, cierre_low_argentina, intro_prechargeswallet_general, cuerpo1_prechargeswallet_general, cuerpo2_prechargeswallet_general, cuerpo3_prechargeswallet_general, cuerpo4_prechargeswallet_general, cierre1_prechargeswallet_general, cierre2_prechargeswallet_general, extrainfo_prechargeswallet_general, intro_prechargeswallet_argentina, cuerpo1_prechargeswallet_argentina, cuerpo2_prechargeswallet_argentina, cuerpo3_prechargeswallet_argentina, cuerpo4_prechargeswallet_argentina, cierre1_prechargeswallet_argentina, cierre2_prechargeswallet_argentina, extrainfo_prechargeswallet_argentina;
            intro_availibility_general = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que nos indicas que no encontraste un Beat cuando necesitabas viajar por la ciudad.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que comentas que no pudiste viajar con nuestra app porque no había usuarios conductores disponibles.", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde nos comentas que ningún usuario conductor aceptó tu solicitud de viaje."]            
            cuerpo_availibility_general = ["Sé que esta situación puede resultar incómoda y lamento lo sucedido. Ten por seguro que estamos trabajando para aumentar la cantidad de usuarios conductores que te puedan llevar a tu destino cuando más lo necesites.", "Entiendo tu molestia y te aseguro que nos estamos esforzando al máximo para que puedas encontrar un Beat disponible en un abrir y cerrar de ojos. Nuestra meta es que viajes rápidamente por toda la ciudad con nuestra app.", "Lamento que hayas pasado por esta incómoda situación. Te puedo asegurar que nos encontramos trabajando las 24 horas del día para que puedas encontrar siempre a un usuario conductor dispuesto a llevarte a tu destino."]
            cierre_availibility_general = ["¡Queremos mejorar para ti! 🙌", "¡Estamos para ayudarte las 24 horas del día! 😌", "¡Haremos lo posible para que siempre viajes feliz con Beat! 🤓"]
            intro_availibility_argentina = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que nos indicás que no encontraste un Beat cuando necesitabas viajar por la ciudad.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que comentás que no pudiste viajar con nuestra app porque no había usuarios conductores disponibles.", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde nos comentás que ningún usuario conductor aceptó tu solicitud de viaje."]            
            cuerpo_availibility_argentina = ["Sé que esta situación puede resultar incómoda y lamento lo sucedido. Tené por seguro que estamos trabajando para aumentar la cantidad de usuarios conductores que te puedan llevar a tu destino cuando más lo necesités.", "Entiendo tu molestia y te aseguro que nos estamos esforzando al máximo para que podás encontrar un Beat disponible en un abrir y cerrar de ojos. Nuestra meta es que viajes rápidamente por toda la ciudad con nuestra app.", "Lamento que hayas pasado por esta incómoda situación. Te puedo asegurar que nos encontramos trabajando las 24 horas del día para que podás encontrar siempre a un usuario conductor dispuesto a llevarte a tu destino."]
            cierre_availibility_argentina = ["¡Queremos mejorar para ti! 🙌", "¡Estamos para ayudarte las 24 horas del día! 😌", "¡Haremos lo posible para que siempre viajes feliz con Beat! 🤓"]
            intro_eb_general = ["Mi nombre es {{ticket.assignee.first_name}} y me comuniqué contigo por teléfono hace unos minutos. Gracias por atender la llamada y me alegra saber que estás bien.", "Mi nombre es {{ticket.assignee.first_name}} y hablé contigo por teléfono hace un momento. Te quiero agradecer por haber atendido la llamada y me alegra saber que te encuentras bien.", "Mi nombre es {{ticket.assignee.first_name}} y hace un momento me comuniqué contigo por teléfono. Gracias por atender la llamada y me alegró enterarme que te encuentras bien."]            
            cuerpo1_ebp_argentina = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_pasajero/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_pasajero/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_pasajero/"]
            cuerpo1_ebp_chile = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/cl/faq_botondeemergencia_pasajero/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/cl/faq_botondeemergencia_pasajero/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/cl/faq_botondeemergencia_pasajero/"]            
            cuerpo1_ebp_colombia = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/co/faq_botondeemergencia_pasajero/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/co/faq_botondeemergencia_pasajero/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/co/faq_botondeemergencia_pasajero/"]
            cuerpo1_ebp_mexico = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/mx/faq_botondeemergencia_pasajero/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/mx/faq_botondeemergencia_pasajero/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/mx/faq_botondeemergencia_pasajero/"]
            cuerpo1_ebp_peru = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/pe/faq_botondeemergencia_pasajero/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/pe/faq_botondeemergencia_pasajero/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/pe/faq_botondeemergencia_pasajero/"]
            cuerpo1_ebd_argentina = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_conductor/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_conductor/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/ar/preguntas-frecuentes-boton-de-emergencia_conductor/"]
            cuerpo1_ebd_chile = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/cl/faq_botondeemergencia_conductor/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/cl/faq_botondeemergencia_conductor/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/cl/faq_botondeemergencia_conductor/"]            
            cuerpo1_ebd_colombia = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/co/faq_botondeemergencia_conductor/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/co/faq_botondeemergencia_conductor/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/co/faq_botondeemergencia_conductor/"]
            cuerpo1_ebd_mexico = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/mx/faq_botondeemergencia_conductor/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/mx/faq_botondeemergencia_conductor/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/mx/faq_botondeemergencia_conductor/"]
            cuerpo1_ebd_peru = ["Con respecto al correcto uso del botón de emergencia, este debe ser presionado solamente para reportar situaciones en las que te encuentres en riesgo. Así podremos darle prioridad a estos casos y actuar de inmediato para ayudar a los usuarios. Encontrarás más información sobre esta función aquí: https://thebeat.co/pe/faq_botondeemergencia_conductor/", "Te comento que el botón de emergencia nos sirve para atender y darle prioridad a situaciones en las que la seguridad de los usuarios esté en riesgo. De esta manera, podremos dedicarnos a la pronta gestión de estos hechos. Puedes encontrar más información al respecto aquí: https://thebeat.co/pe/faq_botondeemergencia_conductor/", "En Beat implementamos el botón de emergencia para poder brindarle la ayuda necesaria a los usuarios que se encuentren en una posible situación de riesgo. Gracias a esta función, le podemos dar prioridad a estos incidentes. Encuentra más información aquí: https://thebeat.co/pe/faq_botondeemergencia_conductor/"]
            cuerpo2_eb_general = ["Si deseas reportar algún incidente, te pido que te comuniques a través de la app entrando a <strong>Menú > Ayuda</strong> para darte una respuesta lo más pronto posible.", "En caso quieras reportar algún inconveniente, lo puedes hacer desde la app entrando a <strong>Menú > Ayuda</strong> y así vamos a atender tu caso a la brevedad.", "¿Quieres reportar algún inconveniente? Solo entra a <strong>Menú > Ayuda</strong> desde la app, escoge la opción adecuada y bríndanos todos los detalles para que podamos atender tu caso rápidamente."]
            cierre_eb_general = ["¡Estamos aquí para ayudarte! 🙌", "¡Estamos disponibles las 24 horas para ayudarte! 😌", "¡Siempre disponibles para ayudarte cuando lo necesites! 🤓"]
            intro_void_argentina = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde indicás que no pudiste realizar un viaje el X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicás que no llegaste a realizar el viaje del X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para ayudarte con el viaje del X_FECHA_X a las X_HORA_X que indicaste que no llegaste a realizar."]            
            cuerpo1_void_argentina = ["Descuida, hemos anulado el viaje en nuestro sistema para que la comisión no sea aplicada y no afecte tu balance. Tené en cuenta que este servicio no será considerado para algún bono en el que hayas participado.", "No te preocupes, este servicio fue anulado en el sistema y la comisión no será aplicada, por lo que tu balance no se verá afectado. Te comento también que este viaje no será tomado en cuenta para ningún bono.", "Te comento que el viaje ha sido anulado en el sistema para que no se aplique la comisión y no disminuya el monto de tu balance. Como el servicio no está activo, no será tomado en cuenta para ningún bono en el que hayas participado."]
            cuerpo2_void_argentina = ["<strong>Beat tip:</strong> iniciá el servicio en la app solo cuando el usuario pasajero haya subido a tu auto, consultes su identidad y confirmes el destino del viaje.💡", "<strong>Beat tip:</strong> iniciá el viaje en la app solo cuando el usuario pasajero esté dentro de tu auto y hayas confirmado su identidad y el destino. 😌", "<strong>Beat tip:</strong> iniciá el servicio solo cuando el usuario pasajero se encuentre a bordo y hayas comprobado su identidad y el destino del viaje. 🙌"]
            cierre_void_argentina = ["¡Sigamos viajando juntos!", "¡Sigamos viajando juntos por toda la ciudad!", "¡Sigamos viajando juntos por toda la ciudad!"]
            intro_void_general = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde indicas que no pudiste realizar un viaje el X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicas que no llegaste a realizar el viaje del X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para ayudarte con el viaje del X_FECHA_X a las X_HORA_X que indicaste que no llegaste a realizar."]            
            cuerpo1_void_general = ["Descuida, hemos anulado el viaje en nuestro sistema para que la comisión no sea aplicada y no afecte tu balance. Ten en cuenta que este servicio no será considerado para algún bono en el que hayas participado.", "No te preocupes, este servicio fue anulado en el sistema y la comisión no será aplicada, por lo que tu balance no ser verá afectado. Te comento también que este viaje no será tomando en cuenta para ningún bono.", "Te comento que el viaje ha sido anulado en el sistema para que no se aplique la comisión y no disminuya el monto de tu balance. Como el servicio no está activo, no será tomado en cuenta para ningún bono en el que hayas participado."]
            cuerpo2_void_general = ["<strong>Beat tip:</strong> inicia el servicio en la app solo cuando el usuario pasajero haya subido a tu auto, consultes su identidad y confirmes el destino del viaje.💡", "<strong>Beat tip:</strong> inicia el viaje en la app solo cuando el usuario pasajero esté dentro de tu auto y hayas confirmado su identidad y el destino. 😌", "<strong>Beat tip:</strong> inicia el servicio solo cuando el usuario pasajero se encuentre a bordo y hayas comprobado su identidad y el destino del viaje. 🙌"]
            cierre_void_general = ["¡Sigamos viajando juntos!", "¡Sigamos viajando juntos por toda la ciudad!", "¡Sigamos viajando juntos por toda la ciudad!"]
            intro_low_general = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para darte más información acerca de las tarifas de nuestra app.", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y atenderé tu reporte sobre las tarifas de nuestros viajes.", "Gracias por escribirnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender tu reporte sobre los precios de nuestros viajes."]            
            cuerpo1_low_general = ["En Beat tenemos los precios más competitivos del mercado para atraer una mayor cantidad de usuarios. 🚗 Contar con miles de pasajeros usando nuestra app significa que podrás hacer muchos viajes y que recibirás solicitudes sin parar cuando estés disponible.", "Somos la app con los precios más accesibles y esto nos permite atraer una mayor cantidad de usuarios. 😎 Más pasajeros usando Beat significa que tu celular no dejará de recibir solicitudes cuando estés disponible con nosotros.", "Nuestras tarifas son las más atractivas para los usuarios que quieren viajar por la ciudad. 😃 Contar con más pasajeros usando Beat significa que no dejarás de recibir alertas cuando te encuentres disponible en nuestra app."]        
            cuerpo2_low_chile = ["¿Deseas generar aún mayores ingresos? Si lo quieres, lo puedes conseguir. 💸 En Beat nos preocupamos para que incrementes tus ganancias y te indicaré cómo hacerlo: <br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Revisa con frecuencia la sección <strong>Bonos</strong> que aparece en la parte inferior de la pantalla principal de la app para que veas los incentivos en los que puedes participar.</li>", "¿Quieres ganar más dinero? ¡Lo puedes conseguir! 💰 Tenemos estas opciones disponibles para ti:<br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Encuentra las campañas que tenemos para ti en la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y gana haciendo viajes.</li>", "Si quieres ganar más dinero, aprovecha las opciones que preparamos para ti:<br><br> <li>Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa. </li> <br> <li>Chequea la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y participa de las campañas que tenemos disponibles.</li>"]
            cuerpo3_low_chile = ["Por si fuera poco, trabajar con Beat te brinda beneficios para que reduzcas tus costos y los puedes encontrar en este enlace. <br> https://thebeat.co/cl/beneficios/","Eso no es todo, formar parte de Beat te da acceso a beneficios exclusivos para que reduzcas tus costos. Encuéntralos aquí. <br> https://thebeat.co/cl/beneficios/","Por si fuera poco, ser un usuario conductor de Beat te brinda beneficios exclusivos que encontrarás aquí. <br> https://thebeat.co/cl/beneficios/"]
            cuerpo2_low_colombia = ["¿Deseas generar aún mayores ingresos? Si lo quieres, lo puedes conseguir. 💸 En Beat nos preocupamos para que incrementes tus ganancias y te indicaré cómo hacerlo: <br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Revisa con frecuencia la sección <strong>Bonos</strong> que aparece en la parte inferior de la pantalla principal de la app para que veas los incentivos en los que puedes participar.</li>", "¿Quieres ganar más dinero? ¡Lo puedes conseguir! 💰 Tenemos estas opciones disponibles para ti:<br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Encuentra las campañas que tenemos para ti en la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y gana haciendo viajes.</li>", "Si quieres ganar más dinero, aprovecha las opciones que preparamos para ti:<br><br> <li>Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa. </li> <br> <li>Chequea la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y participa de las campañas que tenemos disponibles.</li>"]
            cuerpo3_low_colombia = ["Por si fuera poco, trabajar con Beat te brinda beneficios para que reduzcas tus costos y los puedes encontrar en este enlace. <br> https://thebeat.co/co/beneficios/","Eso no es todo, formar parte de Beat te da acceso a beneficios exclusivos para que reduzcas tus costos. Encuéntralos aquí. <br> https://thebeat.co/co/beneficios/","Por si fuera poco, ser un usuario conductor de Beat te brinda beneficios exclusivos que encontrarás aquí. <br> https://thebeat.co/co/beneficios/"]
            cuerpo2_low_mexico = ["¿Deseas generar aún mayores ingresos? Si lo quieres, lo puedes conseguir. 💸 En Beat nos preocupamos para que incrementes tus ganancias y te indicaré cómo hacerlo: <br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Revisa con frecuencia la sección <strong>Bonos</strong> que aparece en la parte inferior de la pantalla principal de la app para que veas los incentivos en los que puedes participar.</li>", "¿Quieres ganar más dinero? ¡Lo puedes conseguir! 💰 Tenemos estas opciones disponibles para ti:<br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Encuentra las campañas que tenemos para ti en la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y gana haciendo viajes.</li>", "Si quieres ganar más dinero, aprovecha las opciones que preparamos para ti:<br><br> <li>Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa. </li> <br> <li>Chequea la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y participa de las campañas que tenemos disponibles.</li>"]
            cuerpo2_low_peru = ["<strong>(PERÚ LITE)</strong><br>¿Deseas generar aún mayores ingresos? Si lo quieres, lo puedes conseguir. 💸 En Beat nos preocupamos para que incrementes tus ganancias y te indicaré cómo hacerlo: <br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Revisa con frecuencia la sección <strong>Bonos</strong> que aparece en la parte inferior de la pantalla principal de la app para que veas los incentivos en los que puedes participar.</li> <br><br><strong>(PERÚ CORE)</strong><br>¿Deseas generar aún mayores ingresos? Si lo quieres, lo puedes conseguir. 💸 Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.", "<strong>(PERÚ LITE)</strong><br>¿Quieres ganar más dinero? ¡Lo puedes conseguir! 💰 Tenemos estas opciones disponibles para ti:<br><br> <li>Comparte el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.</li> <br> <li>Encuentra las campañas que tenemos para ti en la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y gana haciendo viajes.</li> <br><br><strong>(PERÚ CORE)</strong><br>¿Quieres ganar más dinero? ¡Lo puedes conseguir! 💰 Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa.", "<strong>(PERÚ LITE)<br>Si quieres ganar más dinero, aprovecha las opciones que preparamos para ti:<br><br> <li>Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y tú ganes si cumplen las condiciones del programa. </li> <br> <li>Chequea la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y participa de las campañas que tenemos disponibles.</li> <br><br><strong<(PERÚ CORE)</strong><br>¿Quieres aumentar tus ganancias? Solo tienes que recomendar Beat. 🙌 Encuentra tu código en la app entrando a <strong>Menú > Referidos</strong> y compártelo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y ganarás si cumplen las condiciones del programa."]
            cuerpo3_low_peru = ["Por si fuera poco, trabajar con Beat te brinda beneficios para que reduzcas tus costos y los puedes encontrar en este enlace. <br> https://thebeat.co/pe/beneficios/","Eso no es todo, formar parte de Beat te da acceso a beneficios exclusivos para que reduzcas tus costos. Encuéntralos aquí. <br> https://thebeat.co/pe/beneficios/","Por si fuera poco, ser un usuario conductor de Beat te brinda beneficios exclusivos que encontrarás aquí. <br> https://thebeat.co/pe/beneficios/"]
            cierre_low_general = ["Espero haberte ayudado con esta información y sé que podrás incrementar tus ganancias. ¡Sigamos viajando juntos por toda la ciudad!", "Confío en que tus ganancias aumentarán usando la información que te brindé. ¡Sigamos viajando juntos por toda la ciudad!", "Sé que esta información te ayudará a generar más dinero con nuestra app. ¡Sigamos viajando juntos por toda la ciudad!"]
            intro_low_argentina = ["Espero haberte ayudado con esta información y sé que podrás incrementar tus ganancias. ¡Sigamos viajando juntos por toda la ciudad!", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y atenderé tu reporte sobre las tarifas de nuestros viajes.", "Gracias por escribirnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender tu reporte sobre los precios de nuestros viajes."]
            cuerpo1_low_argentina = ["En Beat tenemos los precios más competitivos del mercado para atraer una mayor cantidad de usuarios. 🚗 Contar con miles de pasajeros usando nuestra app significa que podrás hacer muchos viajes y que recibirás solicitudes sin parar cuando estés disponible.", "Somos la app con los precios más accesibles y esto nos permite atraer una mayor cantidad de usuarios. 😎 Más pasajeros usando Beat significa que tu celular no dejará de recibir solicitudes cuando estés disponible con nosotros.", "Nuestras tarifas son las más atractivas para los usuarios que quieren viajar por la ciudad. 😃 Contar con más pasajeros usando Beat significa que no dejarás de recibir alertas cuando te encuentres disponible en nuestra app."]
            cuerpo2_low_argentina = ["¿Deseas generar aún mayores ingresos? Si lo querés, lo podés conseguir. 💸 En Beat nos preocupamos en que vos incrementes tus ganancias y te indicaré cómo hacerlo: <br><br> <li>Compartí el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y vos ganés si cumplen las condiciones del programa.</li> <br> <li>Revisá con frecuencia la sección <strong>Bonos</strong> que aparece en la parte inferior de la pantalla principal de la app para que veas las campañas en las que podés participar.</li>", "¿Querés ganar más dinero? ¡Lo podés conseguir! 💰 Tenemos estas opciones disponibles para vos: <br><br> <li>Compartí el código que encontrarás en la app en <strong>Menú > Referidos</strong> para que tus familiares, amigos o conocidos se registren como usuarios conductores y vos ganes si cumplen las condiciones del programa.</li> <br> <li>Encontrá las campañas que tenemos para ti en la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y ganá haciendo viajes.</li>", "Si querés ganar más dinero, aprovechá las opciones que preparamos para vos: <br><br> <li>Encontrá tu código en la app entrando a <strong>Menú > Referidos</strong> y compartilo con tus familiares, amigos o conocidos para que se registren como usuarios conductores y vos ganés si cumplen las condiciones del programa.</li> <br> <li>Chequea la sección <strong>Bonos</strong> (parte inferior de la pantalla principal de la app) y participá de las campañas que tenemos disponibles.</li>"]
            cierre_low_argentina = ["Espero haberte ayudado con esta información y sé que podrás incrementar tus ganancias. ¡Sigamos viajando juntos por toda la ciudad!", "Confío en que tus ganancias aumentarán usando la información que te brindé. ¡Sigamos viajando juntos por toda la ciudad!", "Sé que esta información te ayudará a generar más dinero con nuestra app. ¡Sigamos viajando juntos por toda la ciudad!"]
            intro_prechargeswallet_general = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender tu reporte sobre los cargos realizados en tu tarjeta.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que nos indicas que se cargó a tu tarjeta la tarifa de un viaje que no realizaste.", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde nos indicas que se hizo un cargo en tu tarjeta por un viaje que no tomaste."]
            cuerpo1_prechargeswallet_general = ["Cada vez que pides un viaje con nuestra app, la tarifa es precargada en tu tarjeta para asegurarnos que cuentes con fondos suficientes. Si tú o el usuario conductor cancelan el servicio, esta cantidad es liberada inmediatamente. Entiendo la molestia que esto pudo causar y queremos compensarte.", "Te comento que los viajes con tarjeta son cargados con anticipación para asegurarnos de que esta tenga fondos suficientes. Si el servicio es cancelado por ti o por el usuario conductor, el monto es liberado inmediatamente.", "En Beat cargamos la tarifa a tu tarjeta cuando pides un viaje para verificar que esta operación se realizará sin problemas. Si el viaje es cancelado por ti o por el usuario conductor, el monto precargado es liberado de manera inmediata. Comprendo que esto te pudo generar una molestia y te queremos compensar."]
            cuerpo2_prechargeswallet_general = ["Por eso, he agregado X_MONTO_X a tu cuenta de usuario pasajero y puedes verificarlo en la app entrando a <strong>Menú > Promociones</strong>. 💸 Este descuento no tiene vencimiento, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido.", "Sé que esto pudo causar una molestia y, para compensar el inconveniente, he agregado X_MONTO_X a tu cuenta Beat. 🤑 Este monto lo puedes ver entrando a <strong>Menú > Promociones</strong>, no tiene fecha de vencimiento, se aplicará automáticamente cuando pidas un nuevo viaje y podrás pagar el resto de la tarifa con el método de pago que desees.", "Acabo de añadir a tu cuenta Beat X_MONTO_X y este monto será aplicado automáticamente la próxima vez que uses nuestra app para viajar por la ciudad. 💰 El descuento que agregué no vence y puedes pagar la cantidad faltante de la tarifa con tarjeta o en efectivo."]
            cuerpo3_prechargeswallet_general = ["Ten en cuenta que el monto que añadí es una cortesía de nuestra parte y adicional a la liberación que tu entidad bancaria está procesando.", "Este descuento es una cortesía de nuestra parte e independiente a la liberación que tu banco está procesando.", "Por otro lado, te comento que el monto añadido es una cortesía de nuestra parte y adicional a la liberación que tu banco se encuentra procesando."]
            cuerpo4_prechargeswallet_general = ["Si aún no ves la cantidad en los movimientos de tu tarjeta, responde este mensaje con el nombre de tu entidad bancaria y también adjunta una foto o captura de pantalla de tu estado de cuenta para consultar por la operación.", "En caso no veas esta operación en tu tarjeta, responde este mensaje con el nombre de tu entidad bancaria y también adjunta una foto o captura de pantalla de tu estado de cuenta para consultar por esto.", "¿Aún no aparece esta operación en tu tarjeta? Responde este mensaje con el nombre de tu entidad bancaria y también adjunta una foto o captura de pantalla de tu estado de cuenta para consultar por la liberación."]
            cierre1_prechargeswallet_general = ["Espero haber resuelto tus dudas y quedo atento a tu respuesta en caso desees enviar la información que te solicité. 🤓", "Espero haber aclarado tus dudas y quedo atento a tu respuesta en caso quieras enviar la información que te he solicitado. 😌", "Espero haber aclarado tu consulta y quedo atento a tu respuesta en caso desees enviar la información que te solicité. 🤓"]
            cierre2_prechargeswallet_general = ["¡Estamos aquí para ayudarte!", "¡Estamos aquí para ayudarte!", "¡Estamos aquí para ayudarte!"]
            extrainfo_prechargeswallet_general = ["<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Vamos a consultar por la liberación y sugiero que preguntes por esta operación a tu entidad bancaria. <br><br>Si tienes alguna otra consulta, puedes comunicarte con nosotros a través de la app entrando a <strong>Menú > Ayuda.</strong>¡Sigamos viajando juntos! 🚗", "<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Consultaremos por la liberación de la tarifa y sugiero que también le preguntes a tu banco por esta operación. <br><br>¿Quieres comunicarte con nosotros por algún otro inconveniente? Contáctanos a través de la app entrando a <strong>Menú > Ayuda.</strong> <br><br>¡Sigamos viajando juntos! 🚙", "<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Vamos a consultar por la liberación y te sugiero que también preguntes por esto a tu banco. <br><br>Si tienes alguna otra consulta, no dudes en comunicarte con nosotros a través de la app entrando a Menú > Ayuda y te respondemos a la brevedad. <br><br>¡Sigamos viajando juntos! 🚗"]
            intro_prechargeswallet_argentina = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender tu reporte sobre los cargos realizados en tu tarjeta.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que nos indicás que se cargó a tu tarjeta la tarifa de un viaje que no realizaste.", "Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte donde nos indicás que se hizo un cargo en tu tarjeta por un viaje que no tomaste."]
            cuerpo1_prechargeswallet_argentina = ["Cada vez que pedís un viaje con nuestra app, la tarifa es precargada en tu tarjeta para asegurarnos que contás con fondos suficientes. Si vos o el usuario conductor cancelan el servicio, esta cantidad es liberada inmediatamente. Entiendo la molestia que esto pudo causar y queremos compensarte.", "Te comento que los viajes con tarjeta son cargados con anticipación para asegurarnos de que esta tenga fondos suficientes. Si el servicio es cancelado por vos o por el usuario conductor, el monto es liberado inmediatamente.", "En Beat cargamos la tarifa a tu tarjeta cuando pedís un viaje para verificar que esta operación se realizará sin problemas. Si el viaje es cancelado por vos o por el usuario conductor, el monto precargado es liberado de manera inmediata. Comprendo que esto te pudo generar una molestia y te queremos compensar."]
            cuerpo2_prechargeswallet_argentina = ["Por eso, he agregado X_MONTO_X a tu cuenta de usuario pasajero y podés verificarlo en la app entrando a <strong<Menú > Promociones</strong>. 💸 Este descuento no tiene vencimiento, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido.", "Sé que esto pudo causar una molestia y, para compensar el inconveniente, he agregado X_MONTO_X a tu cuenta Beat. 🤑 Este monto lo podés ver entrando a <strong>Menú > Promociones</strong>, no tiene fecha de vencimiento, se aplicará automáticamente cuando pidas un nuevo viaje y podrás pagar el resto de la tarifa con el método de pago que desees.", "Acabo de añadir a tu cuenta Beat X_MONTO_X y este monto será aplicado automáticamente la próxima vez que uses nuestra app para viajar por la ciudad. 💰 El descuento que agregué no vence y podés pagar la cantidad faltante de la tarifa con tarjeta o en efectivo."]
            cuerpo3_prechargeswallet_argentina = ["Tené en cuenta que el monto que añadí es una cortesía de nuestra parte y adicional a la liberación que tu entidad bancaria está procesando.", "Este descuento es una cortesía de nuestra parte e independiente a la liberación que tu banco está procesando.", "Por otro lado, te comento que el monto añadido es una cortesía de nuestra parte y adicional a la liberación que tu banco se encuentra procesando."]
            cuerpo4_prechargeswallet_argentina = ["Si aún no ves la operación en los movimientos de tu tarjeta, respondé este mensaje con el nombre de tu entidad bancaria y también adjuntá una foto o captura de pantalla de tu estado de cuenta para consultar por el reembolso.", "En caso no veas esta operación en tu tarjeta, respondé este mensaje con el nombre de tu entidad bancaria y también adjuntá una foto o captura de pantalla de tu estado de cuenta para consultar por esto.", "¿Aún no aparece esta operación en tu tarjeta? Respondé este mensaje con el nombre de tu entidad bancaria y también adjuntá una foto o captura de pantalla de tu estado de cuenta para consultar por la liberación."]
            cierre1_prechargeswallet_argentina = ["Espero haber resuelto tus dudas y quedo atento a tu respuesta en caso desees enviar la información que te solicité. 🤓", "Espero haber aclarado tus dudas y quedo atento a tu respuesta en caso quieras enviar la información que te he solicitado. 😌", "Espero haber aclarado tu consulta y quedo atento a tu respuesta en caso desees enviar la información que te solicité. 🤓"]
            cierre2_prechargeswallet_argentina = ["¡Estamos aquí para ayudarte!", "¡Estamos aquí para ayudarte!", "¡Estamos aquí para ayudarte!"]
            extrainfo_prechargeswallet_argentina = ["<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Vamos a consultar por la liberación y sugiero que preguntés por esta operación a tu entidad bancaria. <br><br>Si tenés alguna otra consulta, podés comunicarte con nosotros a través de la app entrando a <strong>Menú > Ayuda.</strong> <br><br>¡Sigamos viajando juntos! 🚗", "<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Consultaremos por la liberación de la tarifa y sugiero que también le preguntés a tu banco por esta operación. <br><br> ¿Querés comunicarte con nosotros por algún otro inconveniente? Contactanos a través de la app entrando a <strong>Menú > Ayuda.</strong> <br><br> ¡Sigamos viajando juntos! 🚙", "<strong>[SI ENVÍA INFORMACIÓN SOLICITADA]</strong> <br>Gracias por enviar la información. Vamos a consultar por la liberación y te sugiero que también preguntes por esto a tu banco. <br><br> Si tenés alguna otra consulta, no dudes en comunicarte con nosotros a través de la app entrando a Menú > Ayuda y te respondemos a la brevedad. <br><br> ¡Sigamos viajando juntos! 🚗"]
            intro_refundunhappened_general = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicas que no tomaste el viaje del X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicas que no llegaste viajar con nuestra app el X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para ayudarte con el viaje del X_FECHA_X a las X_HORA_X que nos indicas que no llegaste a realizar."]
            cuerpo1_refundunhappened_general = ["Sé que esta no es la experiencia que buscas cuando quieres viajar con Beat por la ciudad. Me encargué de registrar lo sucedido en el sistema para tenerlo presente y tomar las acciones necesarias en caso el usuario conductor repita este comportamiento.", "Entiendo la molestia que esta situación te pudo causar. Voy a registrar lo sucedido en nuestro sistema y realizaremos las gestiones necesarias para evitar incidentes como este ocurran nuevamente.", "Te pido disculpas porque esta no es la experiencia que queremos que tengas cuando uses nuestra app. Registraré lo ocurrido en el sistema y vamos a tomar las medidas necesarias para evitar que esto se repita."]
            cuerpo2_refundunhappened_general = ["Descuida, he reembolsado los X_MONTO_X que fueron cargados a tu tarjeta. Te pido que tengas un poco de paciencia, ya que el tiempo necesario para que veas la devolución depende únicamente de tu banco y puede tomar algunos días.", "Descuida, me encargué de procesar el reembolso de los X_MONTO_X por el servicio que no hiciste con Beat. Te comento que la devolución depende únicamente de tu banco y podría demorar algunos días.", "Acabo de procesar la devolución de los X_MONTO_X por este viaje que no tomaste. Ten en cuenta que el reembolso depende únicamente de tu banco y podría demorar algunos días."]
            cuerpo3_refundunhappened_general = ["Queremos compensarte por este mal rato, así que añadí un cupón de X_MONTO_X en tu cuenta Beat que podrás ver en la app entrando a <strong>Menú > Promociones</strong>. 💰 Este descuento estará vigente por siete días, será aplicado automáticamente en tu siguiente viaje y podrás pagar la diferencia con tu método de pago preferido.", "Para compensar esta mala experiencia, he agregado un cupón de X_MONTO_X en tu cuenta y puedes verlo en la app entrando a <strong>Menú > Promociones</strong>. 🙌 Este descuento es válido por siete días, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido.", "Para compensar este inconveniente, agregué un cupón de X_MONTO_X en tu cuenta de usuario pasajero y puedes verlo en la app entrando a <strong>Menú > Promociones</strong>. 💸 Este descuento es válido por siete días, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido."]
            cierre1_refundunhappened_general = ["Si tienes alguna otra consulta, no dudes en comunicarte con nosotros a través de la app entrando a <strong>Menú > Ayuda</strong>.", "¿Quieres comunicarte con nosotros por algún otro inconveniente? Contáctanos a través de la app entrando a <strong>Menú > Ayuda.</strong>", "Espero haber resuelto tu consulta y no olvides que nos puedes contactar las 24 horas del día."]
            cierre2_refundunhappened_general = ["¡Estamos disponibles todo el día para ayudarte! 🤓", "¡Sigamos viajando juntos! 🚗", "¡Estamos para ayudarte! 😌"]
            intro_refundunhappened_argentina = ["Gracias por comunicarte con nosotros. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicás que no tomaste el viaje del X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para atender el reporte en el que indicas que no llegaste viajar con nuestra app el X_FECHA_X a las X_HORA_X.", "Gracias por contactarnos. Mi nombre es {{ticket.assignee.first_name}} y estoy aquí para ayudarte con el viaje del X_FECHA_X a las X_HORA_X que nos indicás que no llegaste a realizar."]
            cuerpo1_refundunhappened_argentina = ["Sé que esta no es la experiencia que buscás cuando querés viajar con Beat por la ciudad. Me encargué de registrar lo sucedido en el sistema para tenerlo presente y tomar las acciones necesarias en caso el usuario conductor repita este comportamiento.", "Entiendo la molestia que esta situación te pudo causar. Voy a registrar lo sucedido en nuestro sistema y realizaremos las gestiones necesarias para evitar incidentes como este ocurran nuevamente.", "Te pido disculpas porque esta no es la experiencia que queremos que tengas cuando uses nuestra app. Registraré lo ocurrido en el sistema y vamos a tomar las medidas necesarias para evitar que esto se repita."]
            cuerpo2_refundunhappened_argentina = ["Descuida, he reembolsado los X_MONTO_X que fueron cargados a tu tarjeta. Te pido que tengas un poco de paciencia, ya que el tiempo necesario para que veas la devolución depende únicamente de tu banco y puede tomar algunos días.", "Descuida, me encargué de procesar el reembolso de los X_MONTO_X por el servicio que no hiciste con Beat. Te comento que la devolución depende únicamente de tu banco y podría demorar algunos días.", "Acabo de procesar la devolución de los X_MONTO_X por este viaje que no tomaste. Tené en cuenta que el reembolso depende únicamente de tu banco y podría demorar algunos días."]
            cuerpo3_refundunhappened_argentina = ["Queremos compensarte por este mal rato, así que añadí un cupón de X_MONTO_X en tu cuenta Beat que podrás ver en la app entrando a <strong>Menú > Promociones</strong>. 💰 Este descuento estará vigente por siete días, será aplicado automáticamente en tu siguiente viaje y podrás pagar la diferencia con tu método de pago preferido.", "Para compensar esta mala experiencia, he agregado un cupón de X_MONTO_X en tu cuenta y podés verlo en la app entrando a <strong>Menú > Promociones</strong>. 🙌 Este descuento es válido por siete días, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido.", "Para compensar este inconveniente, agregué un cupón de X_MONTO_X en tu cuenta de usuario pasajero y podés verlo en la app entrando a <strong>Menú > Promociones</strong>. 💸 Este descuento es válido por siete días, se aplicará automáticamente en tu próximo viaje y podrás pagar la diferencia con tu método de pago preferido."]
            cierre1_refundunhappened_argentina = ["Si tenés alguna otra consulta, no dudes en comunicarte con nosotros a través de la app entrando a <strong>Menú > Ayuda</strong>.", "¿Querés comunicarte con nosotros por algún otro inconveniente? Contactanos a través de la app entrando a <strong>Menú > Ayuda</strong>.", "Espero haber resuelto tu consulta y no olvides que nos puedes contactar las 24 horas del día."]
            cierre2_refundunhappened_argentina = ["¡Estamos disponibles todo el día para ayudarte! 🤓", "¡Sigamos viajando juntos! 🚗", "¡Estamos para ayudarte! 😌"]


            function randGen() {
              return Math.floor(Math.random() * 5);
            }
            function sentence() {
              var rand1 = Math.floor(Math.random() * 2);
              var rand2 = Math.floor(Math.random() * 2);
              var rand3 = Math.floor(Math.random() * 2);
              var rand4 = Math.floor(Math.random() * 2);
              var rand5 = Math.floor(Math.random() * 2);
              var rand6 = Math.floor(Math.random() * 2);
              var rand7 = Math.floor(Math.random() * 2);
              var rand8 = Math.floor(Math.random() * 2);
              var rand9 = Math.floor(Math.random() * 2);

                if (document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "availibility") {
                var content = intro_availibility_general[rand4] + "<br>" + "<br>" + cuerpo_availibility_general[rand5] + "<br>" + "<br>" + cierre_availibility_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              } 
                if (document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "availibility") {
                var content = intro_availibility_general[rand4] + "<br>" + "<br>" + cuerpo_availibility_general[rand5] + "<br>" + "<br>" + cierre_availibility_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              } 
                if (document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "availibility") {
                var content = intro_availibility_general[rand4] + "<br>" + "<br>" + cuerpo_availibility_general[rand5] + "<br>" + "<br>" + cierre_availibility_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }
                if (document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "availibility") {
                var content = intro_availibility_general[rand4] + "<br>" + "<br>" + cuerpo_availibility_general[rand5] + "<br>" + "<br>" + cierre_availibility_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }  
                if(document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "availibility") {
                var content = intro_availibility_argentina[rand7] + "<br>" + "<br>" + cuerpo_availibility_argentina[rand8] + "<br>" + "<br>" + cierre_availibility_argentina[rand9];
                document.getElementById("sentence").innerHTML = content;
              }                
              if (document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "ebd") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebd_argentina[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              } 
              if (document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "ebd") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebd_chile[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }                 
              if (document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "ebd") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebd_colombia[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }
              if (document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "ebd") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebd_mexico[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }  
              if (document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "ebd") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebd_peru[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }  
              if (document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "ebp") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebp_argentina[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              } 
              if (document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "ebp") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebp_chile[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }                 
              if (document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "ebp") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebp_colombia[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }
              if (document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "ebp") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebp_mexico[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }  
              if (document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "ebp") {
                var content = intro_eb_general[rand4] + "<br>" + "<br>" + cuerpo1_ebp_peru[rand5] + "<br>" + "<br>" + cuerpo2_eb_general[rand5] + "<br>" + "<br>" + cierre_eb_general[rand6];
                document.getElementById('sentence').innerHTML = content;
              }                  
              if(document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "void") {
                var content = intro_void_argentina[rand7] + "<br>" + "<br>" + cuerpo1_void_argentina[rand8] + "<br>" + "<br>" + cuerpo2_void_argentina[rand8] + "<br>" + "<br>" + cierre_void_argentina[rand9];
                document.getElementById("sentence").innerHTML = content;
              }
             if(document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "void") {
                var content = intro_void_general[rand7] + "<br>" + "<br>" + cuerpo1_void_general[rand8] + "<br>" + "<br>" + cuerpo2_void_general[rand8] + "<br>" + "<br>" + cierre_void_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }
             if(document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "void") {
                var content = intro_void_general[rand7] + "<br>" + "<br>" + cuerpo1_void_general[rand8] + "<br>" + "<br>" + cuerpo2_void_general[rand8] + "<br>" + "<br>" + cierre_void_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }
             if(document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "void") {
                var content = intro_void_general[rand7] + "<br>" + "<br>" + cuerpo1_void_general[rand8] + "<br>" + "<br>" + cuerpo2_void_general[rand8] + "<br>" + "<br>" + cierre_void_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }
             if(document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "void") {
                var content = intro_void_general[rand7] + "<br>" + "<br>" + cuerpo1_void_general[rand8] + "<br>" + "<br>" + cuerpo2_void_general[rand8] + "<br>" + "<br>" + cierre_void_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              } 
             if(document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "low") {
                var content = intro_low_general[rand5] + "<br>" + "<br>" + cuerpo1_low_general[rand6] + "<br>" + "<br>" + cuerpo2_low_chile[rand7] + "<br>" + "<br>" + cuerpo3_low_chile[rand8] + "<br>" + "<br>" + cierre_low_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              } 
             if(document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "low") {
                var content = intro_low_general[rand5] + "<br>" + "<br>" + cuerpo1_low_general[rand6] + "<br>" + "<br>" + cuerpo2_low_colombia[rand7] + "<br>" + "<br>" + cuerpo3_low_colombia[rand8] + "<br>" + "<br>" + cierre_low_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }            
             if(document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "low") {
                var content = intro_low_general[rand5] + "<br>" + "<br>" + cuerpo1_low_general[rand6] + "<br>" + "<br>" + cuerpo2_low_mexico[rand7] + "<br>" + "<br>" + cierre_low_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }  
             if(document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "low") {
                var content = intro_low_general[rand5] + "<br>" + "<br>" + cuerpo1_low_general[rand6] + "<br>" + "<br>" + cuerpo2_low_peru[rand7] + "<br>" + "<br>" + cuerpo3_low_peru[rand8] + "<br>" + "<br>" + cierre_low_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              } 
                             if(document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "low") {
                var content = intro_low_argentina[rand5] + "<br>" + "<br>" + cuerpo1_low_argentina[rand6] + "<br>" + "<br>" + cuerpo2_low_argentina[rand7] + "<br>" + "<br>" + cierre_low_argentina[rand9];
                document.getElementById("sentence").innerHTML = content;
              } 
                             if(document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "prechargeswallet") {
                var content = intro_prechargeswallet_general[rand5] + "<br>" + "<br>" + cuerpo1_prechargeswallet_general[rand6] + "<br>" + "<br>" + cuerpo2_prechargeswallet_general[rand7] + "<br>" + "<br>" + cuerpo3_prechargeswallet_general[rand8] + "<br>" + "<br>" + cuerpo4_prechargeswallet_general[rand6] + "<br>" + "<br>" + cierre1_prechargeswallet_general[rand9] + "<br>" + "<br>" + cierre2_prechargeswallet_general[rand7] + "<br>" + "<br>" + extrainfo_prechargeswallet_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              } 
                             if(document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "prechargeswallet") {
                var content = intro_prechargeswallet_general[rand5] + "<br>" + "<br>" + cuerpo1_prechargeswallet_general[rand6] + "<br>" + "<br>" + cuerpo2_prechargeswallet_general[rand7] + "<br>" + "<br>" + cuerpo3_prechargeswallet_general[rand8] + "<br>" + "<br>" + cuerpo4_prechargeswallet_general[rand6] + "<br>" + "<br>" + cierre1_prechargeswallet_general[rand9] + "<br>" + "<br>" + cierre2_prechargeswallet_general[rand7] + "<br>" + "<br>" + extrainfo_prechargeswallet_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }  
                             if(document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "prechargeswallet") {
                var content = intro_prechargeswallet_general[rand5] + "<br>" + "<br>" + cuerpo1_prechargeswallet_general[rand6] + "<br>" + "<br>" + cuerpo2_prechargeswallet_general[rand7] + "<br>" + "<br>" + cuerpo3_prechargeswallet_general[rand8] + "<br>" + "<br>" + cuerpo4_prechargeswallet_general[rand6] + "<br>" + "<br>" + cierre1_prechargeswallet_general[rand9] + "<br>" + "<br>" + cierre2_prechargeswallet_general[rand7] + "<br>" + "<br>" + extrainfo_prechargeswallet_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }  
                             if(document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "prechargeswallet") {
                var content = intro_prechargeswallet_general[rand5] + "<br>" + "<br>" + cuerpo1_prechargeswallet_general[rand6] + "<br>" + "<br>" + cuerpo2_prechargeswallet_general[rand7] + "<br>" + "<br>" + cuerpo3_prechargeswallet_general[rand8] + "<br>" + "<br>" + cuerpo4_prechargeswallet_general[rand6] + "<br>" + "<br>" + cierre1_prechargeswallet_general[rand9] + "<br>" + "<br>" + cierre2_prechargeswallet_general[rand7] + "<br>" + "<br>" + extrainfo_prechargeswallet_general[rand9];
                document.getElementById("sentence").innerHTML = content;
              }  
                             if(document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "prechargeswallet") {
                var content = intro_prechargeswallet_argentina[rand5] + "<br>" + "<br>" + cuerpo1_prechargeswallet_argentina[rand6] + "<br>" + "<br>" + cuerpo2_prechargeswallet_argentina[rand7] + "<br>" + "<br>" + cuerpo3_prechargeswallet_argentina[rand8] + "<br>" + "<br>" + cuerpo4_prechargeswallet_argentina[rand6] + "<br>" + "<br>" + cierre1_prechargeswallet_argentina[rand9] + "<br>" + "<br>" + cierre2_prechargeswallet_argentina[rand7] + "<br>" + "<br>" + extrainfo_prechargeswallet_argentina[rand9];
                document.getElementById("sentence").innerHTML = content;
              }   
             if(document.getElementById("Country").value == "Co" && document.getElementById("Macro").value == "refundunhappened") {
                var content = intro_refundunhappened_general[rand5] + "<br>" + "<br>" + cuerpo1_refundunhappened_general[rand6] + "<br>" + "<br>" + cuerpo2_refundunhappened_general[rand7] + "<br>" + "<br>" + cuerpo3_refundunhappened_general[rand8] + "<br>" + "<br>" + cierre1_refundunhappened_general[rand9] + "<br>" + "<br>" + cierre2_refundunhappened_general[rand7];
                document.getElementById("sentence").innerHTML = content;
              }  
             if(document.getElementById("Country").value == "Cl" && document.getElementById("Macro").value == "refundunhappened") {
                var content = intro_refundunhappened_general[rand5] + "<br>" + "<br>" + cuerpo1_refundunhappened_general[rand6] + "<br>" + "<br>" + cuerpo2_refundunhappened_general[rand7] + "<br>" + "<br>" + cuerpo3_refundunhappened_general[rand8] + "<br>" + "<br>" + cierre1_refundunhappened_general[rand9] + "<br>" + "<br>" + cierre2_refundunhappened_general[rand7];
                document.getElementById("sentence").innerHTML = content;
              } 
             if(document.getElementById("Country").value == "Mx" && document.getElementById("Macro").value == "refundunhappened") {
                var content = intro_refundunhappened_general[rand5] + "<br>" + "<br>" + cuerpo1_refundunhappened_general[rand6] + "<br>" + "<br>" + cuerpo2_refundunhappened_general[rand7] + "<br>" + "<br>" + cuerpo3_refundunhappened_general[rand8] + "<br>" + "<br>" + cierre1_refundunhappened_general[rand9] + "<br>" + "<br>" + cierre2_refundunhappened_general[rand7];
                document.getElementById("sentence").innerHTML = content;
              }  
             if(document.getElementById("Country").value == "Pe" && document.getElementById("Macro").value == "refundunhappened") {
                var content = intro_refundunhappened_general[rand5] + "<br>" + "<br>" + cuerpo1_refundunhappened_general[rand6] + "<br>" + "<br>" + cuerpo2_refundunhappened_general[rand7] + "<br>" + "<br>" + cuerpo3_refundunhappened_general[rand8] + "<br>" + "<br>" + cierre1_refundunhappened_general[rand9] + "<br>" + "<br>" + cierre2_refundunhappened_general[rand7];
                document.getElementById("sentence").innerHTML = content;
              } 
             if(document.getElementById("Country").value == "Ar" && document.getElementById("Macro").value == "refundunhappened") {
                var content = intro_refundunhappened_argentina[rand5] + "<br>" + "<br>" + cuerpo1_refundunhappened_argentina[rand6] + "<br>" + "<br>" + cuerpo2_refundunhappened_argentina[rand7] + "<br>" + "<br>" + cuerpo3_refundunhappened_argentina[rand8] + "<br>" + "<br>" + cierre1_refundunhappened_argentina[rand9] + "<br>" + "<br>" + cierre2_refundunhappened_argentina[rand7];
                document.getElementById("sentence").innerHTML = content;
              }                  
            }

        function code() {
              if(document.getElementById("Macro").value == "availibility") {
          document.getElementById("code").innerHTML = "_";
              } 
              if(document.getElementById("Macro").value == "ebd") {
          document.getElementById("code").innerHTML = "_";
              }  
             if(document.getElementById("Macro").value == "ebp") {
          document.getElementById("code").innerHTML = "_";
              }  
             if(document.getElementById("Macro").value == "prechargeswallet") {
          document.getElementById("code").innerHTML = "Precharges_wallet";
              }              
            if(document.getElementById("Macro").value == "refundunhappened") {
          document.getElementById("code").innerHTML = "Unhappend_ride";
              }
        }
        function tag() {
              if(document.getElementById("Macro").value == "availibility") {
          document.getElementById("tag").innerHTML = "cant_find_driver_pass";
              } 
              if(document.getElementById("Macro").value == "ebd") {
          document.getElementById("tag").innerHTML = "eb_not_emergency_driver";
              }  
             if(document.getElementById("Macro").value == "ebp") {
          document.getElementById("tag").innerHTML = "eb_not_emergency_driver";
              }  
             if(document.getElementById("Macro").value == "prechargeswallet") {
          document.getElementById("tag").innerHTML = "Precharges_wallet_compensation";
              }              
            if(document.getElementById("Macro").value == "refundunhappened") {
          document.getElementById("tag").innerHTML = "Unhappend_ride_charge_pass";
              }
            if(document.getElementById("Macro").value == "low") {
          document.getElementById("tag").innerHTML = "Low_fare";
              }
            if(document.getElementById("Macro").value == "apolp") {
          document.getElementById("tag").innerHTML = "Apologies_pass";
              }   
            if(document.getElementById("Macro").value == "apold") {
          document.getElementById("tag").innerHTML = "Apologies_driver";
              }            
            if(document.getElementById("Macro").value == "void") {
          document.getElementById("tag").innerHTML = "Void_ride";
              }            
        }

            var btn = document.getElementById("boton1");
            btn.addEventListener("click", sentence);
            btn.addEventListener("click", code);
            btn.addEventListener("click", tag);
